navbar:
  blog_title: 漯河小桔国际贸易有限公司

index:
  slogan:
    enable: true
    text: 我们是专业的防爆配电箱厂家,提供各种规格尺寸的配电箱。配电箱接线图、线路图、安装及装饰画等相关信息均有提供。低压配电箱、家用配电箱、照明配电箱、动力配电箱等可根据您的需求定制。配电箱防爆、价格优惠,欢迎咨询

footer:
  beian:
    enable: true
    icp_text: 豫ICP备2023014966号-1
    police_text: 豫公网安备 41110202000388号 
    police_code: 41110202000388
 
about:
  avatar: /static/images/logo_ele.png
  name: "漯河小桔国际贸易有限公司"
  intro: "漯河小桔国际贸易有限公司"
  icons:
    # - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
    # - { class: 'iconfont icon-douban-fill', link: 'https://douban.com', tip: '豆瓣' }
    # - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }